In [1]:
# Support Vector Machine (SVM)

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv('final_dataset.csv')
X = dataset.iloc[:, 2:8].values
y = dataset.iloc[:, 8].values

In [3]:
dataset

140.84770028312096  38.914299394660276  81.32  55.19  7.64  \
0               140.844412           38.912714  81.32  55.19  7.64   
1               140.851338           38.912466  81.32  55.19  7.64   
2               140.851296           38.898872  58.88  34.62  7.03   
3               140.861927           38.906827  73.66  48.76  7.52   
4               140.841398           38.890289  43.78  28.42  6.83   
...                    ...                 ...    ...    ...   ...   
349482          142.050235           39.951233  32.97  31.25  7.16   
349483          142.051676           39.960073  32.91  31.19  7.16   
349484          142.053117           39.968913  32.83  31.12  7.15   
349485          142.053838           39.973332  32.75  31.05  7.15   
349486          142.054559           39.977752  32.75  31.05  7.15   

           2.6925886  1  4  1.1  
0       2.692589e+00  1  4    1  
1       2.692589e+00  1  4    1  
2       2.692589e+00  1  5    1  
3       2.692589e+00  1  4    1  
4       2.692589e+00  1  5    1  
...              ... .. ..  ...  
349482 -3.402824e+38  9  0    0  
349483 -3.402824e+38  9  0    0  
349484 -3.402824e+38  9  0    0  
349485 -3.402824e+38  9  0    0  
349486 -3.402824e+38  9  0    0  

[349487 rows x 9 columns]

In [4]:
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [5]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)


In [6]:
X_test

array([[ 4.9190000e+01,  3.3300000e+01,  7.2200000e+00, -3.4028235e+38,
         1.0000000e+00,  0.0000000e+00],
       [ 3.0370000e+01,  4.8680000e+01,  7.6200000e+00,  1.5921820e+00,
         2.0000000e+00,  1.2000000e+01],
       [ 5.0000000e+01,  4.1280000e+01,  7.6700000e+00,  3.2573166e+00,
         1.0000000e+00,  1.0000000e+00],
       ...,
       [ 3.4670000e+01,  3.2800000e+01,  7.2300000e+00, -3.4028235e+38,
         9.0000000e+00,  0.0000000e+00],
       [ 5.7220000e+01,  3.1420000e+01,  7.1400000e+00,  6.2330437e-01,
         1.0000000e+00,  5.0000000e+00],
       [ 3.7980000e+01,  1.9750000e+01,  6.4800000e+00,  1.0994775e+00,
         1.0000000e+00,  5.0000000e+00]])

In [7]:
X_train

array([[ 3.1150000e+01,  3.7440000e+01,  7.4000000e+00,  4.9636800e-01,
         2.0000000e+00,  5.0000000e+00],
       [ 3.1100000e+01,  1.8350000e+01,  6.4600000e+00,  4.9997690e-01,
         9.0000000e+00,  0.0000000e+00],
       [ 1.8100000e+01,  1.5080000e+01,  6.1100000e+00,  1.1797338e+00,
         7.0000000e+00,  4.0000000e+00],
       ...,
       [ 3.6330000e+01,  4.2960000e+01,  7.5800000e+00,  5.9676180e-01,
         2.0000000e+00,  5.0000000e+00],
       [ 4.3590000e+01,  5.6450000e+01,  8.0200000e+00,  3.1602284e-01,
         2.0000000e+00,  5.0000000e+00],
       [ 3.3760000e+01,  3.1960000e+01,  7.1900000e+00, -3.4028235e+38,
         9.0000000e+00,  0.0000000e+00]])

In [8]:
y_train

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [9]:
len(X_train)

244640

In [10]:
len(X_test)

104847

In [11]:
# Fitting SVM to the Training set
from sklearn.svm import SVC
model=SVC()

In [13]:
model.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [14]:
model.score(X_test,y_test)

0.968859385580894

In [18]:
import matplotlib.pyplot as plt

In [20]:
# Predicting the Test set results
y_pred = model.predict(X_test)

In [16]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
print((cm[0][0]+cm[1][1])/(cm[0][0]+cm[0][1]+cm[1][0]+cm[1][1]))

[[101582      0]
 [  3265      0]]
0.968859385580894


In [17]:
print(cm[0][0])
print(cm[1][0])

101582
3265
